baseURL = 'https://JuliusPinsker.github.io/Summer-Summit-2026/'
languageCode = 'de'
title = 'FAPS Summer Summit 2026'
theme = ''

[params]
  description = 'Kompletter Vergleich f√ºr das FAPS Summer Summit 2026'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
